language: go

go_import_path: 4d63.com/optional

go:
  - tip
  - 1.8

os:
  - linux

script:
  - go vet
  - go test . -coverprofile=coverage-1.txt
  - go test ./template -coverprofile=coverage-2.txt

after_success:
  - cat coverage-1.txt coverage-2.txt > coverage.txt
  - bash <(curl -s https://codecov.io/bash)
